### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by gbadenes** [drlight17/kibana-menu-hide#1]
Hello @drlight17,

How are you doing? I'm having issues installing the plugin on kibana (opendistro), these are the versions I'm using:

```
opendistro-for-elasticsearch-kibana:1.13.1 
opendistro-for-elasticsearch:1.13.1
```

Kibana and Elastic versions are ```7.10.2```

I updated the ```packages.json``` accordingly:
```
"kibana": {
    "version": "7.10.2"
  }
```

This is the error I get:

```
$ ./kibana-plugin install file:///tmp/kibana-menu-hide-master.zip
Found previous install attempt. Deleting...
Attempting to transfer from file:///tmp/kibana-menu-hide-master.zip
Transferring 1159 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /usr/share/kibana/node_modules/yauzl/index.js:187:14
    at /usr/share/kibana/node_modules/yauzl/index.js:631:5
    at /usr/share/kibana/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive" 
```

I googled it but couldn't find the issue.

Any help is welcome! thanks in advance :)

**Comment by drlight17** [comment]
Hi, @gbadenes .
I didn't test plugin with newer then 7.7.0 version.
Anyway, try the following:
1) stop kibana service
`service kibana stop`
2) unpack plugin zip to /usr/share/kibana/plugins/kibana-menu-hide
3) remove all /usr/share/kibana/optimize folder contents
`rm -rf /usr/share/kibana/optimize/*`
4) start kibana service
`service kibana start`
5) check that plugin successfully installed
`/usr/share/kibana/bin/kibana-plugin --allow-root list`
the output must be like:
```
kibana-menu-hide@0.1.4
opendistro-alerting@1.8.0.0
opendistro-anomaly-detection-kibana@1.8.0.0
opendistro-sql-workbench@1.8.0.0
opendistro_index_management_kibana@1.8.0.0
opendistro_security@1.8.0.0
```
6) check kibana log for other errors
7) if no errors in log - try to login to kibana

Hope this helps.

**Comment by gbadenes** [comment]
Hi @drlight17 thanks for your quick reply, unfortunatelly it didn't work. I am still troubleshooting and will let you know if I find the issue. Regards

**Comment by jgough** [comment]
How do I actually build the zip file to install it?  Do I need to use generate_plugin.js in kibana?

**Comment by drlight17** [comment]
> How do I actually build the zip file to install it? Do I need to use generate_plugin.js in kibana?

Hello. There is no need to build something. Just unzip the [archive](https://github.com/drlight17/kibana-menu-hide/archive/refs/heads/master.zip) to /usr/share/kibana/plugins/kibana-menu-hide.
Follow [the instruction](https://github.com/drlight17/kibana-menu-hide/issues/1#issuecomment-814395912) above.
Make sure you have version 7.7.0 of Kibana as I didn't test it with other ones.
